IMDB Clone
Technigo/project-movies pull request #123
Opened 2020-11-08 18:20 UTC by karanmann

Project Movies
Making a multipage React.Js site (Single Page Application) by fetching data from FreeMovieDB.

Tech Used
React.JS, JSX, CSS

The problem
I faced problems with the image loading before the fetch completed causing a 404 error.

View it live
https://imdb-clone-site.netlify.app/

2020-11-11 21:20 UTC, MindstormingAB requested changes
Well done Karan! You seem to deal easily with useEffect, useState, params and BrowserRouter, fetch and API.
In addition to the requirements, you made the layout working on tablets and desktops.
Before I can approve your project, I'd like you to:
- check that your code is written correctly: mind the indentation and make sure that you stick to one approach when it comes to semi-colons (everywhere or mandatory only) and quotation marks (' or ").
- adapt the size of your backdrop image
- remove the unused code/styling/files
- make the movie page responsive on mobile
- make sure that the "Know more" link will open in a different window

2020-11-11 21:20 UTC, MindstormingAB commented on code/src/index.css
> +}
Great that you have a media query for the desktop view. It works well on tablet but I miss a mobile view. 📵

2020-11-23 12:39 UTC, EmOlsz commented on code/src/components/Footer.js
> +import TechnigoLogo from '../img/technigo.svg'
Uppercase names are reserved for components only. Here we should rather have :

```
import technigoLogo from '../img/technigo.svg'
```

2020-11-23 12:39 UTC, EmOlsz commented on code/src/components/MoviePage.js
> +    <>
No need for React fragment here since you return only one element - `.movie-page-background`

2021-03-09 11:26 UTC, closed without merging