Movies project - Marjaana Tienaho
Technigo/project-movies pull request #128
Opened 2020-11-08 19:42 UTC by MayaBlixt

Link to my deployed project:
https://marjaanasmovies.netlify.app/

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2020-11-11 13:23 UTC, LillanEriksson requested changes
Nice work Marjaana! It looks great! Clean and readable. Would you just fix the 404 not found-page? :)

2020-11-11 13:23 UTC, LillanEriksson commented on code/public/index.html
Really nice favicon and great that you added og:tags

2020-11-11 13:23 UTC, LillanEriksson commented on code/src/App.js
> +          <NotFound />
This route does not seem to work, I did not manage to get to it, it just displayed netlifys 404 not found page. It did not work in my project either, so guess we'll have to look into why it works on our local machines, but not  when deployed.

2020-11-23 16:51 UTC, EmOlsz commented on code/src/components/MovieCard.js
> +        <section className='movie-card'>
There are some wrong indentations in this components

2020-11-23 16:51 UTC, EmOlsz commented on code/src/pages/MovieDetails.js
> +import BackArrow from '../components/icons8-back-arrow-64.png';
Uppercase naming is reserved for components only, not images. it should rather be :

```
import backArrow from '../components/icons8-back-arrow-64.png';
```

2020-11-23 16:51 UTC, EmOlsz commented on code/src/pages/NotFound.js
> +import NotFoundImg from '../components/404.jpg';
Same here

2021-03-09 11:26 UTC, closed without merging