Movies project - Andrea Larsson & Astrid Persson
Technigo/project-movies pull request #156
Opened 2021-04-01 19:24 UTC by Aepera

https://movies-project-react.netlify.app/

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2021-04-07 12:42 UTC, Pauan8 requested changes
Great clean code and a nice project that works as intended. Good job 🥇 !!
Just clean up the console.log :)

Request change: remove console.log in deployed project

2021-04-07 12:42 UTC, Pauan8 commented on code/src/pages/MovieDetails.js
> +    .catch(err => console.error(err))
Deployed projects should not contain any console.log!

2021-04-07 12:42 UTC, Pauan8 commented on code/src/pages/MoviesList.js
> +            release_date={movie.release_date}
Here it would be enough to write: 
`<Movie`
`{...movie}`   
( as long as the props has the same name as the json objects this will be enough)

2021-04-07 12:42 UTC, Pauan8 commented on code/src/pages/MovieDetails.js
> +              <p className='details-text'>{movieDetails.overview}</p>
Nice and clear CSS-naming 💯

2021-04-07 12:42 UTC, Pauan8 commented on code/src/pages/MovieDetails.js
> +
It might be a bit of a personal taste thing, but ESLint isn't to happy about blank rows.

2021-04-07 12:42 UTC, Pauan8 commented on code/src/pages/MoviesList.js
> +  },[])
Possibly want a catch error here?

2021-04-14 16:29 UTC, KarolCislowski requested changes
Nice project but please remove all console outputs.

2021-04-14 16:29 UTC, KarolCislowski commented on code/src/pages/MoviesList.js
> +    <>
You have only one section so you do not need `<></>` here.

2021-04-24 16:52 UTC, KarolCislowski approved these changes

2021-10-31 18:03 UTC, closed without merging