Caroline & Pauline
Technigo/project-movies pull request #164
Opened 2021-04-02 17:41 UTC by Pauan8

Movies

2021-04-06 17:12 UTC, darcywinterhill approved these changes
Clean and easy-to-read responsive project. 
Super! 🎇✨

/Darcy & Ann-Sofi

2021-04-06 17:12 UTC, darcywinterhill commented on code/src/index.css
> +.movie-card__image-container {
Clear and obvious classnames for your elements ✨

2021-04-06 17:12 UTC, darcywinterhill commented on code/src/pages/PopularList.js
> +  const API_URL =
A suggestion is to store the  API's in their own file to reduce the amount of code in the components/pages files 🏷

2021-04-06 17:12 UTC, darcywinterhill commented on code/src/components/BackLink.js
> +    <a className="back-link" href="/">
Is there a reason why this is an < a  > and not a < Link >? 🐱‍👤

2021-04-06 17:12 UTC, darcywinterhill commented on code/src/pages/MovieDetails.js
> +      .catch((error) => console.log(error));
What we know we shouldn't use console.log on deployed sites 🎆

2021-04-13 17:32 UTC, KarolCislowski requested changes
Nice project but please remove all console outputs.

2021-04-13 17:32 UTC, KarolCislowski commented on code/src/App.js
> +import { BrowserRouter as Router, Switch, Route } from "react-router-dom";
instead of typing BrowserRouter you just type Router in your code.

2021-04-13 17:32 UTC, KarolCislowski commented on code/src/pages/PopularList.js
> +      .catch((error) => console.log(error));
👮🏻

2021-04-24 16:52 UTC, KarolCislowski approved these changes

2021-10-31 18:02 UTC, closed without merging