Week 12 - Project movies, Isabella Markskog & Sandra Wallén
Technigo/project-movies pull request #166
Opened 2021-04-03 08:48 UTC by IsabellaM5

**Link to our deployed project**
https://musing-noether-fb9258.netlify.app/

**Our reflections on how this week's project turned out**
We did all the blue level requirements. We also did some stretch goals on red and black level.

It was a fun and challenging project! React Router is a great feature, can't wait to deep dive more into React!

One problem that we encountered though was when we tried to move the useParams from the components MovieList and MovieDetails to App.js, it made the node_modules crash. We tried to fix it but ended up moving our code to a new repo instead (this repo).

**Things we'd like to have clarified or explained in more detail**
We would've like to hear more about useHistory and its different methods and use cases. For instance, we know that our component BackLink isn't working as we would've wanted it (it's not dynamic), which is something that we might have been able to fix if we were presented with more information.

/Isabella & Sandra 🐯🐯

2021-04-07 07:33 UTC, annalenksjo approved these changes
Hey! 
This is a really nice project.

The page looks great. It was fun that you did a bit of your own styling and take on it. Nice with a landing page. The landing page could have had a bit more content :) 
Clean code and descriptive naming!

Really like that the movie category gets 'marked' when you have chosen it. 

We like the reflection on what to do if you had more time. 
Maybe also do a catch error thing? Good that you pointed out the problem with the back-link :)

No problems in the console. 

Good job 🐯 !

2021-04-07 07:33 UTC, annalenksjo commented on code/src/pages/MovieDetails.js
> +      .catch(err => console.error(err))
Maybe remove the console.err 😂

2021-04-07 07:33 UTC, annalenksjo commented on code/public/assets/Changa/OFL.txt
> +
👍

2021-04-07 07:33 UTC, annalenksjo commented on README.md
> +
Good explanatory ReadMe

2021-04-13 16:52 UTC, KarolCislowski requested changes
Nice project but please remove all console outputs.

All you need to know about useHistory you can find here: [https://reactrouter.com/web/api/history](https://reactrouter.com/web/api/history).

2021-04-13 16:52 UTC, KarolCislowski commented on code/src/pages/MovieDetails.js
> +      .catch(err => console.error(err))
For Sure

2021-04-13 16:52 UTC, KarolCislowski commented on code/src/pages/MovieDetails.js
> +          <div className="backdrop-img" style={{ backgroundImage: `linear-gradient(180deg, rgba(0,0,0,0) 70%, rgba(0,0,0,1) 100%), url(${URL_BACKDROP(movieSpecs.backdrop_path)})`}}>
Remember to break long lines into a few lines.

2021-04-15 14:48 UTC, IsabellaM5 commented
Hi Karol, 

We have now removed all console outputs in accordance with request :) 

/Isabella & Sandra

2021-04-24 16:44 UTC, KarolCislowski approved these changes

2021-10-31 18:02 UTC, closed without merging