Project Movies - Laima & Malin
Technigo/project-movies pull request #169
Opened 2021-04-04 11:04 UTC by leelalaim

2021-04-07 16:04 UTC, jessika-hage approved these changes
Such a nice project! :D Had just a few tiny comments. Great job!! :D

2021-04-07 16:04 UTC, jessika-hage commented on code/src/components/MovieCard.css
> +}
Here you could have instead made the hover effect on the whole link (and added a class and hover effect on that one) and then put a rgba background color with opacity in .title-date. Cause now when hovering over the links the effect disappears when you get over the text.

2021-04-12 19:14 UTC, KarolCislowski requested changes
Nice project but please remove all console outputs.

2021-04-12 19:14 UTC, KarolCislowski commented on code/src/pages/MovieDetails.jsx
> +        console.log(json);
🚓 👮🏻

2021-05-06 08:48 UTC, leelalaim commented
Requested changes were made

2021-05-31 05:20 UTC, KarolCislowski approved these changes
Great work 👍🏻

2021-10-31 18:02 UTC, closed without merging