Technigo Week 12 - Project Movies - Malin Göthe & Lars Söderman
Technigo/project-movies pull request #173
Opened 2021-04-04 17:08 UTC by M4L5

Link to my deployed project: 
https://sharp-montalcini-473ded.netlify.app/

My reflections on how this week's project turned out: 
Lars and I worked very well together and we are both happy with the result. 

Things I'd like to have clarified or explained in more detail:

2021-04-07 18:26 UTC, liaback-lowstett reviewed
Awesome work! Looks really good 👍 

We noticed that when you realod the detail page you get the message "page not found" , take a look at this solution in Stack-overflow and you might solve it: https://stackoverflow.com/c/technigo/questions/990

/Felicia, Sofia & Caroline

2021-04-07 18:26 UTC, liaback-lowstett commented on code/src/components/Home.js
> +            .catch(err => console.error(err))
No console in production 😉

2021-04-07 18:26 UTC, liaback-lowstett commented on code/src/components/Home.js
> +                    <MovieElement {...movie} />
Nice  use of spread operator!

2021-04-07 18:26 UTC, liaback-lowstett commented on code/src/index.css
> +  object-fit: cover;
Smart to place it here

2021-04-07 18:26 UTC, liaback-lowstett commented on code/src/pages/Details.js
> +    // }
Remove? 🤔

2021-04-07 18:26 UTC, liaback-lowstett commented on code/src/pages/Details.js
> +                .catch(err => console.error(err))
No console in production 😉

2021-04-10 17:46 UTC, KarolCislowski commented on code/src/components/Home.js
> +            .catch(err => console.error(err))
👮🏻

2021-04-10 17:46 UTC, KarolCislowski commented on code/src/pages/Details.js
> +    // }
for sure 😸

2021-04-10 17:48 UTC, KarolCislowski requested changes
Nice project but you need to clean it a little from console outputs and commented out pieces of code. 
You need to work also on your grid:
![image](https://user-images.githubusercontent.com/50926159/114279590-bbd25500-9a35-11eb-97b4-7e10d1afeb81.png)

2021-05-31 05:23 UTC, KarolCislowski approved these changes
Great work 👍🏻

2021-10-31 18:02 UTC, closed without merging