project-movies: Maria Pogosjan & Maidelin Rubio
Technigo/project-movies pull request #175
Opened 2021-04-04 19:00 UTC by MariaPogosjan

Link to my deployed project:

https://movie-netflix.netlify.app/

My reflections on how this week's project turned out:
It was a fun project and good to understand how to create multiple pages. 

Things I'd like to have clarified or explained in more detail:

2021-04-07 14:45 UTC, FD000 reviewed
Very beautiful app. We really liked the styiling. All that remains is some responsiveness for mobile viewports. Keep up the good work!
// Team DD, Martin D & Fethullah D

2021-04-07 14:45 UTC, FD000 commented on code/src/index.css
> +.detail-background {
When you are re-sizing the screen, the background picture stretches and is not responsive. Try using `object-fit: cover ` as styling to this picture and everything will work fine.

2021-04-07 14:45 UTC, FD000 commented on code/src/index.css
> +  .detail-content {
Maybe you could add a detail semi-transparent background to separate text from the backdrop, which will increase readability.

2021-04-07 14:45 UTC, FD000 commented on code/src/index.css
> +@media (min-width: 1200px) {
![image](https://user-images.githubusercontent.com/74493943/113883048-1a8d9980-97be-11eb-80b5-13c0d7d9db2e.png) 
The movie title and the ratings are two separate boxes.  Maybe we could instead have them in same box and create a span after the movie title and then add the rating there to make sure it follows the title as the text wraps.

2021-04-07 14:45 UTC, FD000 commented on code/src/components/Loading.js
> +      <Loader
Fantastic, very beautiful loader!

2021-04-07 14:45 UTC, FD000 commented on code/src/index.css
> +.filter-btn {
Beautiful buttons when changing movie filter. Its easy and smooth to change category

2021-04-07 14:45 UTC, FD000 commented on code/public/index.html
> +    <link rel="icon" type="image/png" href="./favicon/popcorn.png">
Very beautiful popcorn favicon, we really liked it :)

2021-04-07 14:45 UTC, FD000 commented on code/src/pages/Detail.js
> +            <img src="../favicon/button.svg" alt="button icom" />
Maybe have the Alternative TItles pointer to point towards right and not left like the Movies pointer above.

2021-04-10 17:25 UTC, KarolCislowski requested changes
Nice project but please remove all console outputs.

To easily create 404 page you need to:
1. throw en error inside of `.then` block,
2. catch it in the `.catch` block and redirect it with `useHistory` hook provided by `React-router`
3. create a separate page(component) where the user will be redirected.
4. extra step if you are using netlify to host your app: create inside the `public` folder the `_redirects` file and save this line in it: `/* /index.html 200`

Try it 🦄

2021-04-10 17:25 UTC, KarolCislowski commented on code/src/pages/MovieList.js
> +      .catch (err => console.dirr(err))
Please remember to remove all console outputs from your code before submitting. 👮🏻

2021-04-14 11:07 UTC, MariaPogosjan commented
Thank you for your feedback! The error message is now fixed :)


*Allt gott, *
*Maria *

----------

Maria Pogosjan
Phone

|   +46 (0)73 69 14 411  <http://sdf/>




Den lör 10 apr. 2021 kl 19:25 skrev Karol Cislowski <
***@***.***>:

> *@KarolCislowski* requested changes on this pull request.
>
> Nice project but please remove all console outputs.
>
> To easily create 404 page you need to:
>
>    1. throw en error inside of .then block,
>    2. catch it in the .catch block and redirect it with useHistory hook
>    provided by React-router
>    3. create a separate page(component) where the user will be redirected.
>    4. extra step if you are using netlify to host your app: create inside
>    the public folder the _redirects file and save this line in it: /*
>    /index.html 200
>
> Try it 🦄
> ------------------------------
>
> In code/src/pages/MovieList.js
> <https://github.com/Technigo/project-movies/pull/175#discussion_r611070707>
> :
>
> > @@ -0,0 +1,28 @@
>
> +import React, { useState, useEffect } from 'react'
>
> +import { API_URL } from '../reusable/urls'
>
> +import { Link } from 'react-router-dom'
>
> +
>
> +import MovieElement from '../components/MovieElement'
>
> +
>
> +const MovieList = ({filterType}) => {
>
> +  const [movieList, setMovieList] = useState([])
>
> +
>
> +  useEffect (() => {
>
> +   fetch(API_URL(filterType))
>
> +      .then(response => response.json())
>
> +      .then(data => setMovieList(data.results))
>
> +      .catch (err => console.dirr(err))
>
>
> Please remember to remove all console outputs from your code before
> submitting. 👮🏻
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/project-movies/pull/175#pullrequestreview-632938477>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMKEYP2UCRHCTMCFCUL6HWTTICCZRANCNFSM42LV5A5A>
> .
>

2021-04-24 16:49 UTC, KarolCislowski approved these changes

2021-10-31 18:03 UTC, closed without merging