Project movies - Therese H & Anna-Kaisa H
Technigo/project-movies pull request #176
Opened 2021-04-04 19:19 UTC by ThereseHag

Link to my deployed project:
https://therese-anna-kaisa-movies.netlify.app/

My reflections on how this week's project turned out:

This week contained a lot of new information to grasp, and we both needed some time to let the info sink it, but the cooperation and pair work has proceeded in a very good way and we've had fun. We started with the structure and then continued with styling. We had some trouble deciding whether to go with displaying 4 movie cards on all screen sizes, or to have 1 for mobile, 2 for tablet and 4 for desktop, but finally decided to go with the later. Working with React still feel more structured and easy to understand than vanilla JS in general. 

Things I'd like to have clarified or explained in more detail:
Nothing in particular, but look forward to learn more about React Router in the future.

2021-04-07 20:30 UTC, dannuzak approved these changes
It was a pleasure checking out your code, we followed the same approach and having the opportunity to see how you solve it taught us a better solution. So thanks for that! There was not much to add cause it was really well done...so keep up the great work! We see great things coming on your way for you two...🔮 🤩

2021-04-07 20:30 UTC, dannuzak commented on code/src/index.css
> +}
This part of the code we consider it to be nested and therefore it needs some indentation, in contrast to all the code above. Two spaces indentation according to Technigo guidelines. 🍻

2021-04-07 20:30 UTC, dannuzak commented on code/src/pages/MovieDetails.js
> +      .catch((err) => console.error(err));
Those went a bit too far in! 😱  😜

2021-04-07 20:30 UTC, dannuzak commented on code/src/pages/MovieDetails.js
> +export const MovieDetails = () => {
We think this component is too good to be true! So clean and tidy that Mari-Condo would be so proud of you! 🤓

2021-04-07 20:30 UTC, dannuzak commented on code/src/pages/moviedetails.css
> +.button-back {
It is great that you created two css files cause it makes it so easy to read, way to go!🤩

2021-04-07 20:30 UTC, dannuzak commented on code/src/reusables/urls.js
> +export const MOVIES_URL = `https://api.themoviedb.org/3/movie/popular?api_key=${api_key}&language=en-US&page=1`;
A separate variable for the api key is a great idea! We have clever foxes in our foxes team! These two fox-mates are proud of you! 🦊🦊

2021-04-10 17:16 UTC, KarolCislowski requested changes
Nice project 🦄  but please remove all console outputs and use `<Link>` component instead of `<a>` elements.

2021-04-10 17:16 UTC, KarolCislowski commented on code/src/components/MovieList.js
> +      .catch((err) => console.error(err));
Please remember to remove all console outputs from your code before submitting. 👮🏻

2021-04-10 17:16 UTC, KarolCislowski commented on code/src/pages/MovieDetails.js
> +          <a href="/" className="button-back">
you should use `<Link to="/">` component provided by the react router. `<a>` restarts your app that should not be happening.

2021-04-24 16:47 UTC, KarolCislowski approved these changes

2021-10-31 18:03 UTC, closed without merging